# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build & Release
        run: |
          sudo apt install convmv sox
          convmv --notest -r -f utf-8 -t windows-1251 ./
          zip TFCRusFull.pk3 -r -9 *
          zip TFCRusFull.pk3 -m -0 cached.wad fonts.wad gfx.wad
          mv TFCRusFull.pk3 ..
          mkdir sound/vox/goldsrc sound/fvox/goldsrc
          for file in sound/vox/*; do sox ${file} -r 22050 sound/vox/goldsrc/${file}; done
          for file in sound/fvox/*; do sox ${file} -r 22050 sound/fvox/goldsrc/${file}; done
          rm -rf sound/vox/*.wav && mv sound/vox/goldsrc/*.wav sound/vox
          rm -rf sound/fvox/*.wav && mv sound/fvox/goldsrc/*.wav sound/fvox
          rm -rf sound/vox/goldsrc sound/fvox/goldsrc
          zip TFCRusFull.zip -r -9 *
          mv ../TFCRusFull.pk3 $PWD
      # Uploads specified files to GitHub Releases
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Release"
          files: |
            TFCRusFull.pk3
            TFCRusFull.zip
